// Package vm contains the deterministic agent execution surface for ZionLayer.\n// Protocol baseline: September 2026.\npackage vm\nimport("encoding/json";"errors";"github.com/zionlayer/zionlayer/core/state";"github.com/zionlayer/zionlayer/core/transaction";"go.uber.org/zap")
type Opcode byte
const(OpStop Opcode=0x00;OpAgentRegister Opcode=0x10;OpAgentSend Opcode=0x11;OpAgentDelegate Opcode=0x12;OpInferProve Opcode=0x20;OpInferVerify Opcode=0x21;OpTokenTransfer Opcode=0x30;OpA2HPost Opcode=0x40;OpA2HClaim Opcode=0x41;OpA2HComplete Opcode=0x42;OpReturn Opcode=0xF3;OpRevert Opcode=0xFD)
var(ErrOutOfGas=errors.New("out of gas");ErrInvalidOpcode=errors.New("invalid opcode");ErrStackUnderflow=errors.New("stack underflow");ErrExecutionReverted=errors.New("execution reverted"))
type ExecutionContext struct{Caller string;Origin string;GasLimit uint64;GasUsed uint64;Height uint64;State *state.StateDB}
func(c *ExecutionContext)GasLeft()uint64{if c.GasUsed>=c.GasLimit{return 0};return c.GasLimit-c.GasUsed}
func(c *ExecutionContext)UseGas(n uint64)error{if n>c.GasLeft(){return ErrOutOfGas};c.GasUsed+=n;return nil}
type AVM struct{logger *zap.Logger;precompiles map[Opcode]PrecompileFunc}
type PrecompileFunc func(*ExecutionContext,[]byte)([]byte,error)
func NewAVM(l *zap.Logger)*AVM{a:=&AVM{logger:l,precompiles:map[Opcode]PrecompileFunc{}};a.registerBuiltins();return a}
func(a *AVM)Execute(c *ExecutionContext,code []byte)([]byte,error){pc:=0;stack:=make([][]byte,0,16);for pc<len(code){op:=Opcode(code[pc]);pc++;if f,ok:=a.precompiles[op];ok{var args []byte;if len(stack)>0{args=stack[len(stack)-1];stack=stack[:len(stack)-1]};o,e:=f(c,args);if e!=nil{return nil,e};if o!=nil{stack=append(stack,o)};continue};switch op{case OpStop:return nil,nil;case OpReturn:if len(stack)==0{return nil,ErrStackUnderflow};return stack[len(stack)-1],nil;case OpRevert:return nil,ErrExecutionReverted;default:return nil,ErrInvalidOpcode}};return nil,nil}
func(a *AVM)ApplyTransaction(c *ExecutionContext,tx *transaction.Tx)error{if e:=tx.VerifySignature();e!=nil{return e};if tx.From!=c.Caller&&c.Caller!="system"{return errors.New("transaction caller mismatch")};if c.State.GetNonce(tx.From)!=tx.Nonce{return errors.New("invalid nonce")};switch tx.Type{case transaction.TxTransfer:if e:=c.UseGas(21000);e!=nil{return e};if e:=c.State.Transfer(tx.From,tx.To,tx.Value);e!=nil{return e};case transaction.TxAgentRegister:if e:=c.UseGas(200000);e!=nil{return e};var d transaction.AgentDID;if e:=json.Unmarshal(tx.Data,&d);e!=nil{return e};if d.Controller!=tx.From{return errors.New("agent controller mismatch")};if e:=c.State.RegisterAgent(d,c.Height);e!=nil{return e};case transaction.TxAgentMessage:if e:=c.UseGas(50000);e!=nil{return e};var m transaction.AgentMessage;if e:=json.Unmarshal(tx.Data,&m);e!=nil{return e};if m.From!=tx.From{return errors.New("message sender mismatch")};c.State.StoreMessage(m);case transaction.TxInferenceReceipt:if e:=c.UseGas(100000);e!=nil{return e};var r transaction.InferenceReceipt;if e:=json.Unmarshal(tx.Data,&r);e!=nil{return e};if r.AgentID==""||len(r.ProverSig)==0{return errors.New("invalid inference receipt")};a.logger.Info("inference receipt accepted after structural validation");case transaction.TxA2HPost:if e:=c.UseGas(80000);e!=nil{return e};var t transaction.A2HTask;if e:=json.Unmarshal(tx.Data,&t);e!=nil{return e};t.AgentID=tx.From;t.ID=t.ComputeID();esc:=escrow(t);if e:=c.State.Transfer(tx.From,esc,t.Reward);e!=nil{return e};if e:=c.State.PostTask(&t,c.Height);e!=nil{_ = c.State.Transfer(esc,tx.From,t.Reward);return e};case transaction.TxA2HClaim:if e:=c.UseGas(30000);e!=nil{return e};var p struct{TaskID string};if e:=json.Unmarshal(tx.Data,&p);e!=nil{return e};if e:=c.State.ClaimTask(p.TaskID,tx.From,c.Height);e!=nil{return e};case transaction.TxA2HComplete:if e:=c.UseGas(40000);e!=nil{return e};var p struct{TaskID string};if e:=json.Unmarshal(tx.Data,&p);e!=nil{return e};t,e:=c.State.CompleteTask(p.TaskID,tx.From);if e!=nil{return e};if e=c.State.Transfer(escrow(*t),tx.From,t.Reward);e!=nil{return e};default:return ErrInvalidOpcode};return c.State.ApplyNonce(tx.From,tx.Nonce)}
func escrow(t transaction.A2HTask)string{return "a2h_escrow_"+t.ID}
func(a *AVM)registerBuiltins(){a.precompiles[OpAgentRegister]=func(c *ExecutionContext,b []byte)([]byte,error){if e:=c.UseGas(200000);e!=nil{return nil,e};var d transaction.AgentDID;if e:=json.Unmarshal(b,&d);e!=nil{return nil,e};return nil,c.State.RegisterAgent(d,c.Height)};a.precompiles[OpAgentSend]=func(c *ExecutionContext,b []byte)([]byte,error){if e:=c.UseGas(50000);e!=nil{return nil,e};var m transaction.AgentMessage;if e:=json.Unmarshal(b,&m);e!=nil{return nil,e};c.State.StoreMessage(m);return nil,nil};a.precompiles[OpA2HPost]=func(c *ExecutionContext,b []byte)([]byte,error){var t transaction.A2HTask;if e:=json.Unmarshal(b,&t);e!=nil{return nil,e};t.AgentID=c.Caller;t.ID=t.ComputeID();if e:=c.State.Transfer(c.Caller,escrow(t),t.Reward);e!=nil{return nil,e};if e:=c.State.PostTask(&t,c.Height);e!=nil{return nil,e};return []byte(t.ID),nil}}
