// Package rpc exposes the bounded JSON-RPC surface of a ZionLayer node.\n// Protocol baseline: September 2026.\npackage rpc\nimport("encoding/json";"fmt";"net/http";"time";"github.com/zionlayer/zionlayer/core/mempool";"github.com/zionlayer/zionlayer/core/state";"github.com/zionlayer/zionlayer/core/transaction";"go.uber.org/zap")
type Request struct{JSONRPC string;Method string;Params json.RawMessage;ID interface{}}
type Response struct{JSONRPC string;Result interface{};Error *RPCError;ID interface{}}
type RPCError struct{Code int;Message string}
type Server struct{state *state.StateDB;pool *mempool.Pool;logger *zap.Logger;port int}
func NewServer(s *state.StateDB,p *mempool.Pool,l *zap.Logger,port int)*Server{return &Server{state:s,pool:p,logger:l,port:port}}
func(s *Server)Start()error{mux:=http.NewServeMux();mux.HandleFunc("/health",s.health);mux.HandleFunc("/",s.handle);srv:=&http.Server{Addr:fmt.Sprintf(":%d",s.port),Handler:http.MaxBytesHandler(mux,2<<20),ReadHeaderTimeout:5*time.Second,ReadTimeout:15*time.Second,WriteTimeout:15*time.Second,IdleTimeout:60*time.Second};return srv.ListenAndServe()}
func(s *Server)handle(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","application/json");w.Header().Set("Cache-Control","no-store");r.Body=http.MaxBytesReader(w,r.Body,2<<20);if r.Method!="POST"{http.Error(w,"POST required",405);return};var q Request;if e:=json.NewDecoder(r.Body).Decode(&q);e!=nil{writeError(w,nil,-32700,"parse error");return};if q.JSONRPC!="2.0"{writeError(w,q.ID,-32600,"jsonrpc must be 2.0");return};var result interface{};var re *RPCError;switch q.Method{case"zion_getBalance":result,re=s.getBalance(q.Params);case"zion_sendTransaction":result,re=s.sendTransaction(q.Params);case"zion_getAgent":result,re=s.getAgent(q.Params);case"zion_getTask":result,re=s.getTask(q.Params);case"zion_getMempoolSize":result=map[string]int{"size":s.pool.Size()};case"zion_chainId":result="0x1";default:re=&RPCError{-32601,"method not found"}};json.NewEncoder(w).Encode(Response{"2.0",result,re,q.ID})}
func(s *Server)getBalance(p json.RawMessage)(interface{},*RPCError){var a []string;if e:=json.Unmarshal(p,&a);e!=nil||len(a)!=1{return nil,&RPCError{-32602,"invalid params"}};x:=s.state.GetAccount(a[0]);return map[string]string{"address":x.Address,"balance":x.Balance.String(),"nonce":fmt.Sprintf("%d",x.Nonce)},nil}
func(s *Server)sendTransaction(p json.RawMessage)(interface{},*RPCError){var a []*transaction.Tx;if e:=json.Unmarshal(p,&a);e!=nil||len(a)!=1{return nil,&RPCError{-32602,"invalid params"}};if e:=s.pool.Add(a[0]);e!=nil{return nil,&RPCError{-32000,e.Error()}};return fmt.Sprintf("0x%x",a[0].Hash()),nil}
func(s *Server)getAgent(p json.RawMessage)(interface{},*RPCError){var a []string;if e:=json.Unmarshal(p,&a);e!=nil||len(a)!=1{return nil,&RPCError{-32602,"invalid params"}};x,e:=s.state.GetAgent(a[0]);if e!=nil{return nil,&RPCError{-32000,e.Error()}};return x,nil}
func(s *Server)getTask(p json.RawMessage)(interface{},*RPCError){var a []string;if e:=json.Unmarshal(p,&a);e!=nil||len(a)!=1{return nil,&RPCError{-32602,"invalid params"}};x,e:=s.state.GetTask(a[0]);if e!=nil{return nil,&RPCError{-32000,e.Error()}};return x,nil}
func(s *Server)health(w http.ResponseWriter,r *http.Request){json.NewEncoder(w).Encode(map[string]string{"status":"ok"})}
func writeError(w http.ResponseWriter,id interface{},c int,m string){json.NewEncoder(w).Encode(Response{"2.0",nil,&RPCError{c,m},id})}
